echo "args: -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc" -smbios type=2 -device usb-kbd,bus=ehci.0,port=2 -global nec-usb-xhci.msi=off -global ICH9-LPC.acpi-pci-hotplug-with-bridge-support=off -cpu Haswell,vendor=GenuineIntel,+kvm_pv_eoi,+kvm_pv_unhalt,+hypervisor,kvm=on"
echo "agent: 1"
echo "balloon: 0"
echo "bios: ovmf"
echo "boot: order=virtio0"
echo "cores: 4"
echo "cpu: Haswell"
echo "ide2: none,media=cdrom"
echo "machine: q35"
echo "memory: 4096"
echo "name: mimacosventura"
echo "net0: virtio=00:00:00:00:00:99,bridge=vmbr0,firewall=1"
echo "numa: 0"
echo "ostype: other"
echo "scsihw: virtio-scsi-single"
echo "sockets: 1"
echo "vga: vmware"

echo "efidisk0: NVMeMVs:20514/vm-20514-disk-0.raw,efitype=4m,size=528K"
